version: '2'
services:
  web:
    image: hdempsey/askcommunity 
    depends_on: 
      - db
    links:
      - db
    environment:
      DB_HOST: db
    ports:
      - 3000:3000
    # command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"] 
    command: ["npm", "start"]
  db:
    image: mongo
    volumes: 
      - mongodata:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
volumes:
  mongodata: 
